language: ruby
services:
  - redis-server
rvm:
  - 1.9.3
  - jruby
  - 2.0.0
before_script:
  - mkdir -p tmp/cache
  - cp -f db/words.sample.csv db/words.csv
  - RAILS_ENV=test bundle exec rake travis:create:db
  - cp -f config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
script: bundle exec rspec spec
env:
  - DB_ADAPTER=mysql RAILS_ENV=test UV_SUBDOMAIN_NAME=uv UV_API_KEY=1 UV_API_SECRET=1 MXIT_CLIENT_ID=1 SHINKA_AUID=1 GA_TRACKING_CODE=UA-00000000-3 FREEPAID_USER=1 FREEPAID_PASS=1 MXIT_VENDOR_ID=1 APP_SECRET_KEY_BASE=1
  - DB_ADAPTER=sqlite3 RAILS_ENV=test UV_SUBDOMAIN_NAME=uv UV_API_KEY=1 UV_API_SECRET=1 MXIT_CLIENT_ID=1 SHINKA_AUID=1 GA_TRACKING_CODE=UA-00000000-3 FREEPAID_USER=1 FREEPAID_PASS=1 MXIT_VENDOR_ID=1 APP_SECRET_KEY_BASE=1
  - DB_ADAPTER=postgresql RAILS_ENV=test UV_SUBDOMAIN_NAME=uv UV_API_KEY=1 UV_API_SECRET=1 MXIT_CLIENT_ID=1 SHINKA_AUID=1 GA_TRACKING_CODE=UA-00000000-3 FREEPAID_USER=1 FREEPAID_PASS=1 MXIT_VENDOR_ID=1 APP_SECRET_KEY_BASE=1